### ISSUE TITLE
Utilizing ShortcutMapper

### ISSUE THREAD

**Issue by luzpaz** [cpyxis/Scribus-InDesignKeys#1]
Hey @cpyxis 
Thanks for this project. Do you use it? Would you care sharing your experience? Also what do you think about implementing your shortcut keys in to http://waldobronchart.github.io/ShortcutMapper/ This way it could bring further adoption of you work to more folks.  Cheers!

(cc @aoloe & @jluc)

**Comment by cpyxis** [comment]
Hi @luzpaz 
I do use this... it's a little helper tool for me as I design using InDesign daily at work, and when I get home, I freelance with Scribus, Inkscape, and Gimp. Scribus has some great default keys, but InDesign keys are faster for me since I use them more, and Scribus has made is super easy to create your own keymapping.

ShortcutMapper looks like a great tool, and it would be awesome to include this! I see the licenses are different, but I'm fine with relicensing my shortcut keys. I could easily pull the default keys too, since there actually is a handful of Scribus shortcuts that don't map to anything in InDesign.
